### PR TITLE
Make shouldComponentUpdate less aggressive

### LINKED ISSUE #144: Connected component prevents all context propagations
Because connected components have aggressive `shouldComponentUpdate`, and `shouldComponentUpdate` doesn't support context, connected components basically stop any other context variables changes to propagate to their children.

Is there a recommended solution to this problem? I found `pure` option (`connect(..., {pure: false})`), which helps, but is there a better way?

### PR DESCRIPTION
**Pull request by rpominov**
This should fix #144 

One test still failing, but I can see how to fix that if this approach make sense.

### CODE REVIEW

**Comment by gaearon** [comment]
How does this work? It isn't obvious to me how state comparison solves the context issue. Can you elaborate?

**Comment by rpominov** [comment]
It basically checks what caused the update. If the update was caused by a context change or some .forceUpdate() call, `state` and `props` will remain the same. So the logic is: if React wants to make and update, and we don't know the reason, just make the update happen.

**Comment by gaearon** [comment]
This makes sense.
I'd just change it to be written a bit differently:

```js
          const stateChanged = nextState !== this.state;
          const propsChanged = !shallowEqual(nextProps, this.props);
          if (!stateChanged && !propsChanged) {
            // No reason to reconcile but we're in shouldComponentUpdate():
            // This is probably due to a context change so we let the update happen.
            return true;
          }

          const storeStateChanged = ...
```

**Comment by gaearon** [comment]
Hmm.. Wouldn't non-essential prop changes then cause a re-render? e.g. `setState()` in parent component passing the same values as props.

**Comment by rpominov** [comment]
> Hmm.. Wouldn't non-essential prop changes then cause a re-render? e.g. setState() in parent component passing the same values as props.

Probably yes. Although this can be handled by the parent component's `shouldComponentUpdate`. This is a trade-off anyway, but I think it better than too aggressive shouldComponentUpdate.

**Comment by rpominov** [comment]
> Hmm.. Wouldn't non-essential prop changes then cause a re-render? e.g. setState() in parent component passing the same values as props.

And this is why the remaining test fails :)

**Comment by gaearon** [comment]
>Although this can be handled by the parent component's shouldComponentUpdate. This is a trade-off anyway, but I think this is better than a too aggressive shouldComponentUpdate.

This was the point of having `shouldComponentUpdate()` on `connect()`. Otherwise it doesn't really give you anything, as prop changes will be common, especially with nested `connect()`s.

If there's no easy fix, I think `{ pure: false}` is the correct solution until React context problem is fixed.

**Comment by rpominov** [comment]
Ok, maybe we could put the `if (!stateChanged && !propsChanged)` check inside `if (!pure) {...}` then? So when `{pure: false}` mode is used we still do less unnecessary work. Or maybe we can have 3 modes?

**Comment by gaearon** [comment]
`{ pure: false }` should disable the check completely. It should update even if you deeply mutate the props—just like React's default `shouldComponentUpdate()` works out of the box.

I don't really want to support three different modes. :-( If you really need this I think you're better off writing your own version of `connect()` that satisfies your needs.

**Comment by rpominov** [comment]
Okay. All this made me think that I probably should not use context the way I use it anyway. Otherwise I'll have have the same issue with my own `shouldCompoentUpdate` methods.

**Pull request closed without merging**
